### ISSUE TITLE
FCM 저장 API 생성

### ISSUE THREAD

**Issue by yxnxj** [Eruna-Jeoruna/jeoruna#6]
## Todo

- [x] Firebase json gitignore
- [x] project dependency
- [x] add firebase config
- [x] add production code

## Notes
- feat/fcm 브랜치에서 진행
